# ==============================================================================
# LiteLLM + Bedrock deploy Makefile
# ==============================================================================
# Setup: cp .env.example .env && edit .env with credentials
# ==============================================================================

STACK_NAME ?= litellm-claude-code
AWS_REGION ?= us-west-2
LITELLM_PORT ?= 4000

# Auto-load .env if present
ifneq (,$(wildcard .env))
  include .env
  export
endif

# ===== Local development =====

.PHONY: deploy-local
deploy-local: ## Start local Docker stack (litellm + postgres + redis)
	@echo "🚀 Starting LiteLLM stack locally..."
	docker-compose up -d
	@echo "⏳ Waiting for services to be healthy..."
	@sleep 8
	@echo "✅ LiteLLM running at http://localhost:$(LITELLM_PORT)"
	@echo "✅ UI:                 http://localhost:$(LITELLM_PORT)/ui/"
	@echo ""
	@echo "Login: admin / $$LITELLM_MASTER_KEY"
	@echo ""
	@echo "Claude Code config:"
	@echo "  export ANTHROPIC_BASE_URL=http://localhost:$(LITELLM_PORT)"
	@echo "  export ANTHROPIC_AUTH_TOKEN=$$LITELLM_MASTER_KEY"
	@echo "  export CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1"
	@echo "  claude --model claude-sonnet-4-6"

.PHONY: test-local
test-local: ## Run local inference smoke test
	curl -s -X POST http://localhost:$(LITELLM_PORT)/v1/messages \
		-H "Authorization: Bearer $$LITELLM_MASTER_KEY" \
		-H "Content-Type: application/json" \
		-d '{"model":"claude-sonnet-4-6","max_tokens":50,"messages":[{"role":"user","content":"Say hello"}]}' | jq .

.PHONY: logs-local
logs-local: ## Tail local logs
	docker-compose logs -f litellm

.PHONY: clean-local
clean-local: ## Remove local containers and volumes
	docker-compose down -v

# ===== AWS one-shot deploy =====

.PHONY: gen-keys
gen-keys: ## (Optional) Write preset credentials to .env.deployed. Skip this if you want CFN auto-generation.
	@echo "🔑 Generating fresh credentials..."
	@printf "LITELLM_MASTER_KEY=sk-%s\nDB_PASSWORD=\n" \
		$$(openssl rand -hex 16) > .env.deployed
	@chmod 600 .env.deployed
	@echo "✅ Saved to .env.deployed (mode 600). DB_PASSWORD left empty so CFN will auto-generate it."

.PHONY: deploy
deploy: ## One-shot AWS deploy (all credentials can be auto-generated by CFN)
	@touch .env.deployed && . ./.env.deployed && \
	echo "🚀 Deploying $(STACK_NAME) to $(AWS_REGION)..." && \
	sam build --template template.yaml && \
	sam deploy \
		--stack-name $(STACK_NAME) \
		--region $(AWS_REGION) \
		--capabilities CAPABILITY_IAM \
		--parameter-overrides \
			"LiteLLMMasterKey=$${LITELLM_MASTER_KEY:-} DBPassword=$${DB_PASSWORD:-} AnthropicApiKey=$${ANTHROPIC_API_KEY:-} LiteLLMLicenseKey=$${LITELLM_LICENSE_KEY:-} CloudFrontPriceClass=$${CLOUDFRONT_PRICE_CLASS:-PriceClass_All}" \
		--resolve-s3 \
		--no-confirm-changeset \
		--no-fail-on-empty-changeset
	@echo ""
	@$(MAKE) creds

.PHONY: creds
creds: ## Show deployed credentials (Master Key + DB Password) and URLs
	@echo "╔═ LiteLLM Credentials ═════════════════════════════════════════"
	@aws cloudformation describe-stacks --stack-name $(STACK_NAME) --region $(AWS_REGION) \
		--query 'Stacks[0].Outputs[?OutputKey==`CloudFrontURL` || OutputKey==`UILoginURL` || OutputKey==`LiteLLMMasterKey` || OutputKey==`DBPassword`].[OutputKey,OutputValue]' \
		--output table
	@echo "╚═══════════════════════════════════════════════════════════════"

.PHONY: status
status: ## Show full stack status and outputs
	@aws cloudformation describe-stacks --stack-name $(STACK_NAME) --region $(AWS_REGION) \
		--query 'Stacks[0].{Status:StackStatus,Outputs:Outputs[*].[OutputKey,OutputValue]}' \
		--output table

.PHONY: get-url
get-url: ## Print just the CloudFront URL
	@aws cloudformation describe-stacks --stack-name $(STACK_NAME) --region $(AWS_REGION) \
		--query 'Stacks[0].Outputs[?OutputKey==`CloudFrontURL`].OutputValue' --output text

.PHONY: test
test: ## Test the deployed stack
	@URL=$$($(MAKE) -s get-url); \
	KEY=$$(aws cloudformation describe-stacks --stack-name $(STACK_NAME) --region $(AWS_REGION) --query 'Stacks[0].Outputs[?OutputKey==`LiteLLMMasterKey`].OutputValue' --output text); \
	echo "Testing $$URL ..." && \
	echo "--- /health/liveliness ---" && \
	curl -s -o /dev/null -w "HTTP %{http_code}\n" $$URL/health/liveliness && \
	echo "--- /v1/messages (sonnet) ---" && \
	curl -s -X POST $$URL/v1/messages \
		-H "Authorization: Bearer $$KEY" \
		-H "Content-Type: application/json" \
		-d '{"model":"claude-sonnet-4-6","max_tokens":30,"messages":[{"role":"user","content":"reply ok"}]}' | jq .

# ===== Operations =====

.PHONY: scale
scale: ## Manually scale ECS (usage: make scale COUNT=5)
	aws ecs update-service \
		--cluster $(STACK_NAME)-cluster \
		--service $$(aws ecs list-services --cluster $(STACK_NAME)-cluster --region $(AWS_REGION) --query 'serviceArns[0]' --output text | xargs basename) \
		--desired-count $(COUNT) \
		--region $(AWS_REGION)

.PHONY: redeploy-tasks
redeploy-tasks: ## Force ECS task restart (pull new image / config)
	aws ecs update-service \
		--cluster $(STACK_NAME)-cluster \
		--service $$(aws ecs list-services --cluster $(STACK_NAME)-cluster --region $(AWS_REGION) --query 'serviceArns[0]' --output text | xargs basename) \
		--force-new-deployment \
		--region $(AWS_REGION) > /dev/null
	@echo "✅ Service redeploy triggered"

.PHONY: logs
logs: ## Tail ECS container logs (last 5 minutes)
	@aws logs tail /ecs/$(STACK_NAME) --since 5m --follow --region $(AWS_REGION)

.PHONY: destroy
destroy: ## ⚠️ Tear down the stack (auto-disables RDS DeletionProtection first)
	@echo "⚠️  Disabling RDS deletion protection..."
	-aws rds modify-db-instance --db-instance-identifier $(STACK_NAME)-db \
		--no-deletion-protection --apply-immediately --region $(AWS_REGION) > /dev/null
	@echo "⚠️  Deleting stack $(STACK_NAME)..."
	aws cloudformation delete-stack --stack-name $(STACK_NAME) --region $(AWS_REGION)
	aws cloudformation wait stack-delete-complete --stack-name $(STACK_NAME) --region $(AWS_REGION)
	@echo "✅ Stack deleted (RDS snapshot retained per DeletionPolicy)"

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-18s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := help
